
<!DOCTYPE HTML>

<html lang="en">

<head>
  <meta charset="utf-8">
  <title>9.2. Recoverable Errors With Result - Rust - W3cubDocs</title>
  
  <meta name="description" content="Most errors aren’t serious enough to require the program to stop entirely. Sometimes, when a function fails, it’s for a reason that you can easily &hellip;">
  <meta name="keywords" content="recoverable, errors, with, result, -, rust">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/rust/book/second-edition/ch09-02-recoverable-errors-with-result/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-6cc8ff3c95d062e2cd87636799240e79e4553263ad7de9cda9464063203db436.css" integrity="sha256-bMj/PJXQYuLNh2NnmSQOeeRVMmOtfenNqUZAYyA9tDY=" crossorigin="anonymous">
  <script type="text/javascript" integrity="sha256-JOOcjTvTbt5QE9AmOH1rrXz8aKKfHMsOthbsjt9CNfk=" crossorigin="anonymous" src="/assets/application-24e39c8d3bd36ede5013d026387d6bad7cfc68a29f1ccb0eb616ec8edf4235f9.js"></script>
  <script src="/json/rust.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2572770204602497",
            enable_page_level_ads: true
        });
  </script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/rust/" class="_nav-link" title="" style="margin-left:0;">Rust</a></span>
  
  <nav class="_nav">
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<div class="_page _rust">
				
				
<h1 id="recoverable-errors-with-result">Recoverable Errors with <code>Result</code>
</h1> <p>Most errors aren’t serious enough to require the program to stop entirely. Sometimes, when a function fails, it’s for a reason that you can easily interpret and respond to. For example, if you try to open a file and that operation fails because the file doesn’t exist, you might want to create the file instead of terminating the process.</p> <p>Recall from “<a href="../ch02-00-guessing-game-tutorial/#handling-potential-failure-with-the-result-type">Handling Potential Failure with the <code>Result</code> Type</a>” in Chapter 2 that the <code>Result</code> enum is defined as having two variants, <code>Ok</code> and <code>Err</code>, as follows:</p> <pre data-language="rust">
# #![allow(unused_variables)]
#fn main() {
enum Result&lt;T, E&gt; {
    Ok(T),
    Err(E),
}
#}</pre> <p>The <code>T</code> and <code>E</code> are generic type parameters: we’ll discuss generics in more detail in Chapter 10. What you need to know right now is that <code>T</code> represents the type of the value that will be returned in a success case within the <code>Ok</code> variant, and <code>E</code> represents the type of the error that will be returned in a failure case within the <code>Err</code> variant. Because <code>Result</code> has these generic type parameters, we can use the <code>Result</code> type and the functions that the standard library has defined on it in many different situations where the successful value and error value we want to return may differ.</p> <p>Let’s call a function that returns a <code>Result</code> value because the function could fail. In Listing 9-3 we try to open a file.</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">use std::fs::File;

fn main() {
    let f = File::open("hello.txt");
}
</pre> <p><span class="caption">Listing 9-3: Opening a file</span></p> <p>How do we know <code>File::open</code> returns a <code>Result</code>? We could look at the standard library API documentation, or we could ask the compiler! If we give <code>f</code> a type annotation that we know is <em>not</em> the return type of the function and then try to compile the code, the compiler will tell us that the types don’t match. The error message will then tell us what the type of <code>f</code> <em>is</em>. Let’s try it! We know that the return type of <code>File::open</code> isn’t of type <code>u32</code>, so let’s change the <code>let f</code> statement to this:</p> <pre data-language="rust">let f: u32 = File::open("hello.txt");
</pre> <p>Attempting to compile now gives us the following output:</p> <pre>error[E0308]: mismatched types
 --&gt; src/main.rs:4:18
  |
4 |     let f: u32 = File::open("hello.txt");
  |                  ^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found enum
`std::result::Result`
  |
  = note: expected type `u32`
             found type `std::result::Result&lt;std::fs::File, std::io::Error&gt;`
</pre> <p>This tells us the return type of the <code>File::open</code> function is a <code>Result&lt;T, E&gt;</code>. The generic parameter <code>T</code> has been filled in here with the type of the success value, <code>std::fs::File</code>, which is a file handle. The type of <code>E</code> used in the error value is <code>std::io::Error</code>.</p> <p>This return type means the call to <code>File::open</code> might succeed and return a file handle that we can read from or write to. The function call also might fail: for example, the file might not exist, or we might not have permission to access the file. The <code>File::open</code> function needs to have a way to tell us whether it succeeded or failed and at the same time give us either the file handle or error information. This information is exactly what the <code>Result</code> enum conveys.</p> <p>In the case where <code>File::open</code> succeeds, the value in the variable <code>f</code> will be an instance of <code>Ok</code> that contains a file handle. In the case where it fails, the value in <code>f</code> will be an instance of <code>Err</code> that contains more information about the kind of error that happened.</p> <p>We need to add to the code in Listing 9-3 to take different actions depending on the value <code>File::open</code> returns. Listing 9-4 shows one way to handle the <code>Result</code> using a basic tool, the <code>match</code> expression that we discussed in Chapter 6.</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) =&gt; file,
        Err(error) =&gt; {
            panic!("There was a problem opening the file: {:?}", error)
        },
    };
}
</pre> <p><span class="caption">Listing 9-4: Using a <code>match</code> expression to handle the <code>Result</code> variants that might be returned</span></p> <p>Note that, like the <code>Option</code> enum, the <code>Result</code> enum and its variants have been imported in the prelude, so we don’t need to specify <code>Result::</code> before the <code>Ok</code> and <code>Err</code> variants in the <code>match</code> arms.</p> <p>Here we tell Rust that when the result is <code>Ok</code>, return the inner <code>file</code> value out of the <code>Ok</code> variant, and we then assign that file handle value to the variable <code>f</code>. After the <code>match</code>, we can use the file handle for reading or writing.</p> <p>The other arm of the <code>match</code> handles the case where we get an <code>Err</code> value from <code>File::open</code>. In this example, we’ve chosen to call the <code>panic!</code> macro. If there’s no file named <em>hello.txt</em> in our current directory and we run this code, we’ll see the following output from the <code>panic!</code> macro:</p> <pre>thread 'main' panicked at 'There was a problem opening the file: Error { repr:
Os { code: 2, message: "No such file or directory" } }', src/main.rs:9:12
</pre> <p>As usual, this output tells us exactly what has gone wrong.</p> <h3 id="matching-on-different-errors">Matching on Different Errors</h3> <p>The code in Listing 9-4 will <code>panic!</code> no matter why <code>File::open</code> failed. What we want to do instead is take different actions for different failure reasons: if <code>File::open</code> failed because the file doesn’t exist, we want to create the file and return the handle to the new file. If <code>File::open</code> failed for any other reason—for example, because we didn’t have permission to open the file—we still want the code to <code>panic!</code> in the same way as it did in Listing 9-4. Look at Listing 9-5, which adds another arm to the <code>match</code>.</p> <p><span class="filename">Filename: src/main.rs</span></p>  <pre data-language="rust">use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) =&gt; file,
        Err(ref error) if error.kind() == ErrorKind::NotFound =&gt; {
            match File::create("hello.txt") {
                Ok(fc) =&gt; fc,
                Err(e) =&gt; {
                    panic!(
                        "Tried to create file but there was a problem: {:?}",
                        e
                    )
                },
            }
        },
        Err(error) =&gt; {
            panic!(
                "There was a problem opening the file: {:?}",
                error
            )
        },
    };
}
</pre> <p><span class="caption">Listing 9-5: Handling different kinds of errors in different ways</span></p> <p>The type of the value that <code>File::open</code> returns inside the <code>Err</code> variant is <code>io::Error</code>, which is a struct provided by the standard library. This struct has a method <code>kind</code> that we can call to get an <code>io::ErrorKind</code> value. The enum <code>io::ErrorKind</code> is provided by the standard library and has variants representing the different kinds of errors that might result from an <code>io</code> operation. The variant we want to use is <code>ErrorKind::NotFound</code>, which indicates the file we’re trying to open doesn’t exist yet.</p> <p>The condition <code>if error.kind() == ErrorKind::NotFound</code> is called a <em>match guard</em>: it’s an extra condition on a <code>match</code> arm that further refines the arm’s pattern. This condition must be true for that arm’s code to be run; otherwise, the pattern matching will move on to consider the next arm in the <code>match</code>. The <code>ref</code> in the pattern is needed so <code>error</code> is not moved into the guard condition but is merely referenced by it. The reason you use <code>ref</code> to create a reference in a pattern instead of <code>&amp;</code> will be covered in detail in Chapter 18. In short, in the context of a pattern, <code>&amp;</code> matches a reference and gives you its value, but <code>ref</code> matches a value and gives you a reference to it.</p> <p>The condition we want to check in the match guard is whether the value returned by <code>error.kind()</code> is the <code>NotFound</code> variant of the <code>ErrorKind</code> enum. If it is, we try to create the file with <code>File::create</code>. However, because <code>File::create</code> could also fail, we need to add an inner <code>match</code> expression as well. When the file can’t be opened, a different error message will be printed. The last arm of the outer <code>match</code> stays the same so the program panics on any error besides the missing file error.</p> <h3 id="shortcuts-for-panic-on-error-unwrap-and-expect">Shortcuts for Panic on Error: <code>unwrap</code> and <code>expect</code>
</h3> <p>Using <code>match</code> works well enough, but it can be a bit verbose and doesn’t always communicate intent well. The <code>Result&lt;T, E&gt;</code> type has many helper methods defined on it to do various tasks. One of those methods, called <code>unwrap</code>, is a shortcut method that is implemented just like the <code>match</code> expression we wrote in Listing 9-4. If the <code>Result</code> value is the <code>Ok</code> variant, <code>unwrap</code> will return the value inside the <code>Ok</code>. If the <code>Result</code> is the <code>Err</code> variant, <code>unwrap</code> will call the <code>panic!</code> macro for us. Here is an example of <code>unwrap</code> in action:</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">use std::fs::File;

fn main() {
    let f = File::open("hello.txt").unwrap();
}
</pre> <p>If we run this code without a <em>hello.txt</em> file, we’ll see an error message from the <code>panic!</code> call that the <code>unwrap</code> method makes:</p> <pre>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
repr: Os { code: 2, message: "No such file or directory" } }',
src/libcore/result.rs:906:4
</pre> <p>Another method, <code>expect</code>, which is similar to <code>unwrap</code>, lets us also choose the <code>panic!</code> error message. Using <code>expect</code> instead of <code>unwrap</code> and providing good error messages can convey your intent and make tracking down the source of a panic easier. The syntax of <code>expect</code> looks like this:</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">use std::fs::File;

fn main() {
    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
</pre> <p>We use <code>expect</code> in the same way as <code>unwrap</code>: to return the file handle or call the <code>panic!</code> macro. The error message used by <code>expect</code> in its call to <code>panic!</code> will be the parameter that we pass to <code>expect</code>, rather than the default <code>panic!</code> message that <code>unwrap</code> uses. Here’s what it looks like:</p> <pre>thread 'main' panicked at 'Failed to open hello.txt: Error { repr: Os { code:
2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
</pre> <p>Because this error message starts with the text we specified, <code>Failed to open hello.txt</code>, it will be easier to find where in the code this error message is coming from. If we use <code>unwrap</code> in multiple places, it can take more time to figure out exactly which <code>unwrap</code> is causing the panic because all <code>unwrap</code> calls that panic print the same message.</p> <h3 id="propagating-errors">Propagating Errors</h3> <p>When you’re writing a function whose implementation calls something that might fail, instead of handling the error within this function, you can return the error to the calling code so that it can decide what to do. This is known as <em>propagating</em> the error and gives more control to the calling code, where there might be more information or logic that dictates how the error should be handled than what you have available in the context of your code.</p> <p>For example, Listing 9-6 shows a function that reads a username from a file. If the file doesn’t exist or can’t be read, this function will return those errors to the code that called this function.</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">
# #![allow(unused_variables)]
#fn main() {
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) =&gt; file,
        Err(e) =&gt; return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&amp;mut s) {
        Ok(_) =&gt; Ok(s),
        Err(e) =&gt; Err(e),
    }
}
#}</pre> <p><span class="caption">Listing 9-6: A function that returns errors to the calling code using <code>match</code></span></p> <p>Look at the return type of the function first: <code>Result&lt;String, io::Error&gt;</code>. This means the function is returning a value of the type <code>Result&lt;T, E&gt;</code> where the generic parameter <code>T</code> has been filled in with the concrete type <code>String</code> and the generic type <code>E</code> has been filled in with the concrete type <code>io::Error</code>. If this function succeeds without any problems, the code that calls this function will receive an <code>Ok</code> value that holds a <code>String</code>—the username that this function read from the file. If this function encounters any problems, the code that calls this function will receive an <code>Err</code> value that holds an instance of <code>io::Error</code> that contains more information about what the problems were. We chose <code>io::Error</code> as the return type of this function because that happens to be the type of the error value returned from both of the operations we’re calling in this function’s body that might fail: the <code>File::open</code> function and the <code>read_to_string</code> method.</p> <p>The body of the function starts by calling the <code>File::open</code> function. Then we handle the <code>Result</code> value returned with a <code>match</code> similar to the <code>match</code> in Listing 9-4, only instead of calling <code>panic!</code> in the <code>Err</code> case, we return early from this function and pass the error value from <code>File::open</code> back to the calling code as this function’s error value. If <code>File::open</code> succeeds, we store the file handle in the variable <code>f</code> and continue.</p> <p>Then we create a new <code>String</code> in variable <code>s</code> and call the <code>read_to_string</code> method on the file handle in <code>f</code> to read the contents of the file into <code>s</code>. The <code>read_to_string</code> method also returns a <code>Result</code> because it might fail, even though <code>File::open</code> succeeded. So we need another <code>match</code> to handle that <code>Result</code>: if <code>read_to_string</code> succeeds, then our function has succeeded, and we return the username from the file that’s now in <code>s</code> wrapped in an <code>Ok</code>. If <code>read_to_string</code> fails, we return the error value in the same way that we returned the error value in the <code>match</code> that handled the return value of <code>File::open</code>. However, we don’t need to explicitly say <code>return</code>, because this is the last expression in the function.</p> <p>The code that calls this code will then handle getting either an <code>Ok</code> value that contains a username or an <code>Err</code> value that contains an <code>io::Error</code>. We don’t know what the calling code will do with those values. If the calling code gets an <code>Err</code> value, it could call <code>panic!</code> and crash the program, use a default username, or look up the username from somewhere other than a file, for example. We don’t have enough information on what the calling code is actually trying to do, so we propagate all the success or error information upward for it to handle appropriately.</p> <p>This pattern of propagating errors is so common in Rust that Rust provides the question mark operator <code>?</code> to make this easier.</p> <h4 id="a-shortcut-for-propagating-errors-the--operator">A Shortcut for Propagating Errors: the <code>?</code> Operator</h4> <p>Listing 9-7 shows an implementation of <code>read_username_from_file</code> that has the same functionality as it had in Listing 9-6, but this implementation uses the <code>?</code> operator.</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">
# #![allow(unused_variables)]
#fn main() {
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&amp;mut s)?;
    Ok(s)
}
#}</pre> <p><span class="caption">Listing 9-7: A function that returns errors to the calling code using the <code>?</code> operator</span></p> <p>The <code>?</code> placed after a <code>Result</code> value is defined to work in almost the same way as the <code>match</code> expressions we defined to handle the <code>Result</code> values in Listing 9-6. If the value of the <code>Result</code> is an <code>Ok</code>, the value inside the <code>Ok</code> will get returned from this expression, and the program will continue. If the value is an <code>Err</code>, the value inside the <code>Err</code> will be returned from the whole function as if we had used the <code>return</code> keyword so the error value gets propagated to the calling code.</p> <p>There is a difference between what the <code>match</code> expression from Listing 9-6 and the <code>?</code> operator do: error values used with <code>?</code> go through the <code>from</code> function, defined in the <code>From</code> trait in the standard library, which is used to convert errors from one type into another. When the <code>?</code> operator calls the <code>from</code> function, the error type received is converted into the error type defined in the return type of the current function. This is useful when a function returns one error type to represent all the ways a function might fail, even if parts might fail for many different reasons. As long as each error type implements the <code>from</code> function to define how to convert itself to the returned error type, the <code>?</code> operator takes care of the conversion automatically.</p> <p>In the context of Listing 9-7, the <code>?</code> at the end of the <code>File::open</code> call will return the value inside an <code>Ok</code> to the variable <code>f</code>. If an error occurs, the <code>?</code> operator will return early out of the whole function and give any <code>Err</code> value to the calling code. The same thing applies to the <code>?</code> at the end of the <code>read_to_string</code> call.</p> <p>The <code>?</code> operator eliminates a lot of boilerplate and makes this function’s implementation simpler. We could even shorten this code further by chaining method calls immediately after the <code>?</code>, as shown in Listing 9-8.</p> <p><span class="filename">Filename: src/main.rs</span></p> <pre data-language="rust">
# #![allow(unused_variables)]
#fn main() {
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&amp;mut s)?;

    Ok(s)
}
#}</pre> <p><span class="caption">Listing 9-8: Chaining method calls after the <code>?</code> operator</span></p> <p>We’ve moved the creation of the new <code>String</code> in <code>s</code> to the beginning of the function; that part hasn’t changed. Instead of creating a variable <code>f</code>, we’ve chained the call to <code>read_to_string</code> directly onto the result of <code>File::open("hello.txt")?</code>. We still have a <code>?</code> at the end of the <code>read_to_string</code> call, and we still return an <code>Ok</code> value containing the username in <code>s</code> when both <code>File::open</code> and <code>read_to_string</code> succeed rather than returning errors. The functionality is again the same as in Listing 9-6 and Listing 9-7; this is just a different, more ergonomic way to write it.</p> <h4 id="the--operator-can-only-be-used-in-functions-that-return-result">The <code>?</code> Operator Can Only Be Used in Functions That Return <code>Result</code>
</h4> <p>The <code>?</code> operator can only be used in functions that have a return type of <code>Result</code>, because it is defined to work in the same way as the <code>match</code> expression we defined in Listing 9-6. The part of the <code>match</code> that requires a return type of <code>Result</code> is <code>return Err(e)</code>, so the return type of the function must be a <code>Result</code> to be compatible with this <code>return</code>.</p> <p>Let’s look at what happens if we use the <code>?</code> operator in the <code>main</code> function, which you’ll recall has a return type of <code>()</code>:</p> <pre data-language="rust">use std::fs::File;

fn main() {
    let f = File::open("hello.txt")?;
}
</pre> <p>When we compile this code, we get the following error message:</p> <pre>error[E0277]: the trait bound `(): std::ops::Try` is not satisfied
 --&gt; src/main.rs:4:13
  |
4 |     let f = File::open("hello.txt")?;
  |             ------------------------
  |             |
  |             the `?` operator can only be used in a function that returns
  `Result` (or another type that implements `std::ops::Try`)
  |             in this macro invocation
  |
  = help: the trait `std::ops::Try` is not implemented for `()`
  = note: required by `std::ops::Try::from_error`
</pre> <p>This error points out that we’re only allowed to use the <code>?</code> operator in a function that returns <code>Result</code>. In functions that don’t return <code>Result</code>, when you call other functions that return <code>Result</code>, you’ll need to use a <code>match</code> or one of the <code>Result</code> methods to handle the <code>Result</code> instead of using the <code>?</code> operator to potentially propagate the error to the calling code.</p> <p>Now that we’ve discussed the details of calling <code>panic!</code> or returning <code>Result</code>, let’s return to the topic of how to decide which is appropriate to use in which cases.</p>
<div class="_attribution">
  <p class="_attribution-p">
    © 2010 The Rust Project Developers<br>Licensed under the Apache License, Version 2.0 or the MIT license, at your option.<br>
    <a href="https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html" class="_attribution-link" target="_blank">https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html</a>
  </p>
</div>

				<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
</amp-auto-ads>
			</div>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
